[package]
name = "filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cozy-chess = "0.3.1"
clap = { version = "4.5.1", features = ["derive"] }
rand = "0.8.5"
